### PR TITLE
Added monetary value to question in json. Value is shown between questions

### PR DESCRIPTION
**Pull request by Bergalerga**

### CODE REVIEW

**Comment by hakloev** [comment]
I like what I see, it will make the thrill level go sky high! :D Is it at thought to add this somewhere else on the page as well, to make it always visible?

**Comment by Bergalerga** [comment]
På toppen kanskje?

**Comment by hakloev** [comment]
I added a quick suggestion on how to handle this :)

**Comment by Bergalerga** [comment]
Hva med som header i question-boksen, eller over question boksen?

**Pull request merged**
